### ISSUE TITLE
Error (and sometimes crash) when selecting Sun before 1 AD

### ISSUE THREAD

**Issue by Atque** [Astrarium/Astrarium#129]
Using 24.9 (Nocturne), there appears to be a problem with the Sun on dates preciding 1 AD. Selecting it, as to display its info, generates a Microsoft .NET Framework error message (unhandled exception), and occasionally a crash. Furthermore, zooming in on the Sun hides the solar disk for some reason.

I managed to copy the error message, and it reads as follows:

> ************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, DateTimeKind kind)
   at Astrarium.Plugins.SolarSystem.SolarRegionSummaryManager.GetSRSForJulianDate(Double jd, Double utcOffset)
   at Astrarium.Plugins.SolarSystem.ViewModels.SolarActivityViewModel.Update()
   at Astrarium.Plugins.SolarSystem.SolarSystemPlugin.GetSolarActivityViewModel(SkyContext ctx, CelestialObject obj)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Astrarium.ViewModels.MainVM.GetObjectInfo(CelestialObject body)
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by AlexanderKrutov** [comment]
Thanks! Will check it.
